// Copyright 2025 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package runtime

import (
	"github.com/prometheus/client_golang/prometheus"
	"sigs.k8s.io/controller-runtime/pkg/metrics"
)

func init() {
	metrics.Registry.MustRegister(
		nodeEvalTotal,
		nodeEvalDuration,
		nodeEvalErrorsTotal,
		runtimeCreationTotal,
		runtimeCreationDuration,
		nodeIgnoredCheckTotal,
		nodeIgnoredTotal,
		nodeReadyCheckTotal,
		nodeNotReadyTotal,
		collectionSize,
	)
}

var (
	nodeEvalTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_eval_total",
			Help: "Total number of node evaluations during reconciliation",
		},
	)

	nodeEvalDuration = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "runtime_node_eval_duration_seconds",
			Help:    "Duration of node evaluations during reconciliation in seconds",
			Buckets: prometheus.DefBuckets,
		},
	)

	nodeEvalErrorsTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_eval_errors_total",
			Help: "Total number of node evaluation errors",
		},
	)

	runtimeCreationTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_creation_total",
			Help: "Total number of runtimes created",
		},
	)

	runtimeCreationDuration = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "runtime_creation_duration_seconds",
			Help:    "Duration of runtime creation setup phase in seconds",
			Buckets: prometheus.DefBuckets,
		},
	)

	nodeIgnoredCheckTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_ignored_check_total",
			Help: "Total number of node includeWhen checks",
		},
	)

	nodeIgnoredTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_ignored_total",
			Help: "Total number of nodes skipped due to includeWhen conditions",
		},
	)

	nodeReadyCheckTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_ready_check_total",
			Help: "Total number of node readyWhen checks",
		},
	)

	nodeNotReadyTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_not_ready_total",
			Help: "Total number of times nodes were not ready and blocked reconciliation",
		},
	)

	collectionSize = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "runtime_collection_size",
			Help:    "Number of items generated by forEach collection expansion",
			Buckets: prometheus.ExponentialBuckets(1, 2, 10),
		},
	)
)
